FROM node:latest as build

WORKDIR /usr/src/app

COPY package*.json ./

COPY . .

RUN npm i

RUN npm run build

FROM nginx:latest

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]